output "Microstep MAG 341C OLED Unknown" {
		mode 3440x1440@144
		scale 1
		alias $desk-wide
}

output "LG Electronics LG ULTRAGEAR 407NTCZB9315" {
	mode 2560x1440@180.06
	scale 1
	transform 90

	alias $desk-tall
}

profile desk {
	output $desk-wide {
		position 1440,0
	}

	output $desk-tall {
		position 0,0
	}
}

profile go {
	output "BOE 0x0BC9 Unknown" {
		mode 2560x1600@165.00
		position 0,0
		scale 1.333
	}
}
